FROM php:8.2-apache

RUN a2enmod rewrite

RUN apt-get update && apt-get install -y unzip git

COPY composer.json composer.lock /var/www/html/

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader

COPY public/ /var/www/html/
COPY vendor/ /var/www/html/vendor/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
